---
- name: Ensure needed packages exists
  package:
    name: "{{ vimplug_packages }}"
    state: present

- block:
  - name: Ensure needed directory exists
    file: 
      path: "{{ vimplug_vim_datadir }}/autoload"
      state: directory

  - name: Check if vim-plug is installed
    stat:
      path: "{{ vimplug_vim_datadir }}/autoload/plug.vim"
    register: vimplug_installed

  - name: Installing vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "{{ vimplug_vim_datadir }}/autoload/plug.vim"
    when: vimplug_installed.stat.isreg is not defined or not vimplug_installed.stat.isreg
  become: "{{ vimplug_become | bool }}"

- block:
  - name: Ensure vimrc exists
    file:
      path: "{{ vimplug_vimrc_path }}"
      state: touch
      modification_time: preserve
      access_time: preserve

  - name: Ensure needed lines exists
    lineinfile:
      path: "{{ vimplug_vimrc_path }}"
      line: "{{ item }}"
      insertbefore: BOF
    loop:
    - call plug#end()
    - "call plug#begin('{{ vimplug_vim_datadir }}/plugged')"

  - name: Putting plugins into vimrc
    lineinfile:
      path: "{{ vimplug_vimrc_path }}"
      line: "Plug '{{ item.name }}'{{ ', ' ~ item.options|list|join(', ') if item.options is defined else '' }}"
      insertbefore: "^call plug#end()"
      firstmatch: yes
    loop: "{{ vimplug_plugins }}"
    when: item is defined
  become: "{{ vimplug_become | bool }}"
  notify: Running PlugInstall
