---
k3s_release_version: v1.22.4+k3s1

# A list of templates used for pre-configuring the cluster.
k3s_server_manifests_templates:
  - calico-installation.yaml.j2

# A list of URLs used for pre-configuring the cluster.
k3s_server_manifests_urls:
  - url: https://docs.projectcalico.org/manifests/tigera-operator.yaml
    filename: tigera-operator.yaml

# A list of URLs used for installing static pod manifests on the control plane.
k3s_server_pod_manifests_urls: []
#  - url: https://some/url/to/manifest.yml
#    filename: manifest.yml

k3s_etcd_datastore: true
k3s_install_hard_links: true
k3s_become_for_all: true
