---
### Example hosts file
all:
  hosts:
  children:
    desktop:
      hosts:
        10.8.0.2:
        192.168.200.95:
    servers:
      hosts:
        localhost:
          ansible_connection: local
        192.168.200.96:
        192.168.200.206:
        192.168.200.207:
