---
### Example hosts file
all:
  hosts:
  children:
    desktop:
      hosts:
        10.10.0.3:
        192.168.200.49:
    servers:
      hosts:
        localhost:
          ansible_connection: local
        192.168.200.31:
        192.168.200.33:
        192.168.200.34:
        192.168.200.35:
        192.168.200.36:
