---
### Example hosts file
all:
  hosts:
    budimanjojo-kmaster1:
      ansible_host: 192.168.200.11
      ip: 192.168.200.11
      access_ip: 192.168.200.11
    budimanjojo-kmaster2:
      ansible_host: 192.168.200.12
      ip: 192.168.200.12
      access_ip: 192.168.200.12
    budimanjojo-kmaster3:
      ansible_host: 192.168.200.13
      ip: 192.168.200.13
      access_ip: 192.168.200.13
  children:
    desktop:
      hosts:
        10.10.0.3:
        192.168.200.49:
    servers:
      hosts:
        localhost:
          ansible_connection: local
        192.168.200.31:
        192.168.200.33:
        192.168.200.34:
        192.168.200.35:
        192.168.200.36:
    kube_control_plane:
      hosts:
        budimanjojo-kmaster1:
        budimanjojo-kmaster2:
        budimanjojo-kmaster3:
    kube_node:
      hosts:
        budimanjojo-kmaster1:
        budimanjojo-kmaster2:
        budimanjojo-kmaster3:
    etcd:
      hosts:
        budimanjojo-kmaster1:
        budimanjojo-kmaster2:
        budimanjojo-kmaster3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
    kubespray:
      children:
        k8s_cluster:
